# Generated by Django 4.1.6 on 2023-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckgroup', models.CharField(max_length=50, verbose_name='Камиони по групи')),
                ('shortname', models.CharField(max_length=100, verbose_name='Късо име')),
                ('longname', models.TextField(blank='True', max_length=1000, verbose_name='Дълго име')),
                ('truckinfo', models.TextField(max_length=1000, verbose_name='Инфо за камиона')),
                ('storedplace', models.CharField(max_length=150, verbose_name='Местодомуване')),
                ('labelident', models.TextField(max_length=200, verbose_name='Етикет идентификация')),
            ],
        ),
    ]
