# Generated by Django 4.0.4 on 2023-02-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckgroup', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=100)),
                ('longname', models.TextField(max_length=1000)),
                ('truckinfo', models.TextField(max_length=1000)),
                ('storedplace', models.CharField(max_length=150)),
                ('labelident', models.TextField(max_length=200)),
            ],
        ),
    ]
