# Generated by Django 4.0.4 on 2023-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucks',
            name='labelident',
            field=models.TextField(max_length=200, verbose_name='Етикет идентификация'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='longname',
            field=models.TextField(blank='True', max_length=1000, verbose_name='Дълго име'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='shortname',
            field=models.CharField(max_length=100, verbose_name='Късо име'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='storedplace',
            field=models.CharField(max_length=150, verbose_name='Местодомуване'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='truckgroup',
            field=models.CharField(max_length=50, verbose_name='Камиони по групи'),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='truckinfo',
            field=models.TextField(max_length=1000, verbose_name='Инфо за камиона'),
        ),
    ]
